import { VendorSubmissionPayload } from './types';

export interface DemoScenario {
  id: string;
  name: string;
  expectedOutcome: 'APPROVED' | 'PENDING' | 'REJECTED';
  description: string;
  payload: VendorSubmissionPayload;
}

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'clean_vendor',
    name: '1. Clean Vendor',
    expectedOutcome: 'APPROVED',
    description: 'Complete submission with matching valid PDF fixtures. Passes all checks.',
    payload: {
      legal_name: 'Acme Technologies Private Limited',
      trade_name: 'Acme Tech',
      country: 'India',
      registered_address: 'Plot 42, Hinjewadi IT Park, Pune, Maharashtra 411057',
      pan: 'ABCDE1234F',
      gstin: '27ABCDE1234F1Z5',
      bank_account_holder: 'ACME TECHNOLOGIES PVT LTD',
      bank_account_number: '1234567890',
      ifsc: 'ABCD0123456',
      document_references: [
        {
          document_type: 'PAN',
          filename: 'pan.pdf',
          storage_reference: 'test-data/clean_vendor/pan.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'GST_CERTIFICATE',
          filename: 'gst_certificate.pdf',
          storage_reference: 'test-data/clean_vendor/gst_certificate.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'BANK_PROOF',
          filename: 'bank_proof.pdf',
          storage_reference: 'test-data/clean_vendor/bank_proof.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'INCORPORATION',
          filename: 'incorporation.pdf',
          storage_reference: 'test-data/clean_vendor/incorporation.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
      ],
    },
  },
  {
    id: 'missing_bank_proof',
    name: '2. Missing Bank Proof',
    expectedOutcome: 'PENDING',
    description: 'Submission missing the bank proof document. Triggers PENDING state requiring documentation.',
    payload: {
      legal_name: 'Harbor Supplies Private Limited',
      trade_name: 'Harbor Supplies',
      country: 'India',
      registered_address: 'Building B, Sea Face Road, Mumbai, Maharashtra 400018',
      pan: 'ABCDE1234F',
      gstin: '27ABCDE1234F1Z5',
      bank_account_holder: 'Harbor Supplies Pvt Ltd',
      bank_account_number: '9876543210',
      ifsc: 'ABCD0123456',
      document_references: [
        {
          document_type: 'PAN',
          filename: 'pan.pdf',
          storage_reference: 'test-data/missing_bank_proof/pan.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'GST_CERTIFICATE',
          filename: 'gst_certificate.pdf',
          storage_reference: 'test-data/missing_bank_proof/gst_certificate.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'INCORPORATION',
          filename: 'incorporation.pdf',
          storage_reference: 'test-data/missing_bank_proof/incorporation.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
      ],
    },
  },
  {
    id: 'name_variation',
    name: '3. Company Name Variation',
    expectedOutcome: 'APPROVED',
    description: 'Legitimate company name variation (e.g. Pvt Ltd vs Private Limited) handled via normalization & AI comparison.',
    payload: {
      legal_name: 'Acme Holdings Private Limited',
      trade_name: 'Acme Holdings',
      country: 'India',
      registered_address: 'Sector 5, Salt Lake, Kolkata, West Bengal 700091',
      pan: 'ABCDE1234F',
      gstin: '27ABCDE1234F1Z5',
      bank_account_holder: 'Acme Trading Pvt Ltd',
      bank_account_number: '5566778899',
      ifsc: 'ABCD0123456',
      document_references: [
        {
          document_type: 'PAN',
          filename: 'pan.pdf',
          storage_reference: 'test-data/name_variation/pan.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'GST_CERTIFICATE',
          filename: 'gst_certificate.pdf',
          storage_reference: 'test-data/name_variation/gst_certificate.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'BANK_PROOF',
          filename: 'bank_proof.pdf',
          storage_reference: 'test-data/name_variation/bank_proof.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'INCORPORATION',
          filename: 'incorporation.pdf',
          storage_reference: 'test-data/name_variation/incorporation.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
      ],
    },
  },
  {
    id: 'identity_conflict',
    name: '4. Material Identity Conflict',
    expectedOutcome: 'REJECTED',
    description: 'Bank account belongs to an entirely different entity (Rival Trading). Triggers REJECTED status.',
    payload: {
      legal_name: 'Acme Technologies Private Limited',
      trade_name: 'Acme Tech',
      country: 'India',
      registered_address: 'Plot 42, Hinjewadi IT Park, Pune, Maharashtra 411057',
      pan: 'ABCDE1234F',
      gstin: '27ABCDE1234F1Z5',
      bank_account_holder: 'Rival Trading Private Limited',
      bank_account_number: '9988776655',
      ifsc: 'ABCD0123456',
      document_references: [
        {
          document_type: 'PAN',
          filename: 'pan.pdf',
          storage_reference: 'test-data/identity_conflict/pan.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'GST_CERTIFICATE',
          filename: 'gst_certificate.pdf',
          storage_reference: 'test-data/identity_conflict/gst_certificate.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'BANK_PROOF',
          filename: 'bank_proof.pdf',
          storage_reference: 'test-data/identity_conflict/bank_proof.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'INCORPORATION',
          filename: 'incorporation.pdf',
          storage_reference: 'test-data/identity_conflict/incorporation.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
      ],
    },
  },
  {
    id: 'tax_mismatch',
    name: '5. Tax Identifier Mismatch',
    expectedOutcome: 'REJECTED',
    description: 'GSTIN state registration contains an embedded PAN that does not match submitted PAN. Triggers REJECTED status.',
    payload: {
      legal_name: 'Apex Global Logistics Private Limited',
      trade_name: 'Apex Logistics',
      country: 'India',
      registered_address: 'GIDC Industrial Estate, Vadodara, Gujarat 390010',
      pan: 'ABCDE1234F',
      gstin: '24XYZAB9876C1Z5',
      bank_account_holder: 'Apex Global Logistics Pvt Ltd',
      bank_account_number: '4455667788',
      ifsc: 'ABCD0123456',
      document_references: [
        {
          document_type: 'PAN',
          filename: 'pan.pdf',
          storage_reference: 'test-data/clean_vendor/pan.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'GST_CERTIFICATE',
          filename: 'gst_certificate.pdf',
          storage_reference: 'test-data/clean_vendor/gst_certificate.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'BANK_PROOF',
          filename: 'bank_proof.pdf',
          storage_reference: 'test-data/clean_vendor/bank_proof.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
        {
          document_type: 'INCORPORATION',
          filename: 'incorporation.pdf',
          storage_reference: 'test-data/clean_vendor/incorporation.pdf',
          processing_status: 'PENDING',
          extracted_fields: {},
          extraction_errors: [],
        },
      ],
    },
  },
];
